### ISSUE TITLE
ESPnow high latency

### ISSUE THREAD

**Issue by Ahmed-Mahmoud23** [leonyuhanov/ESP32_ESPIDF_ESPNOW#1]
Hi
I came across the same problem but fixing the wifi rate doesn't change anything. I even cloned your code , disabled AMPDU TX&RX and then ran it and still getting 6-8 ms on my esp32s2. is there anything else im not paying attention to?

**Comment by leonyuhanov** [comment]
I havnt looked at this in ages on the espidf, so no idea.
